# Generated by Django 2.0.13 on 2020-01-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='container',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('entry', models.CharField(max_length=100)),
                ('output', models.CharField(max_length=100)),
                ('arrival', models.DateTimeField(auto_now=True)),
                ('departure', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=100)),
                ('load', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('temparature', models.FloatField()),
                ('humidity', models.FloatField()),
            ],
        ),
    ]
